pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }

    tools {
        maven "M3"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('test-sonar') {
                    sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=my-app"
                }
            }
        }

        stage("Quality Gate check"){
            steps{
                timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
            
        }
        
        stage("Archive"){
            steps{
               archiveArtifacts artifacts: "target/*.jar", fingerprint: true 
            }
            
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
